### ISSUE TITLE
mkdir: cannot create directory ‘cov-analysis’: File exists

### ISSUE THREAD

**Issue by jiangxincode** [vapier/coverity-scan-action#7]
https://github.com/jiangxincode/ApkToolBoxGUI/actions/runs/3355305882/jobs/5559459905
https://github.com/jiangxincode/ApkToolBoxGUI/actions/runs/3365122061/jobs/5580260735

The first link is an push event on master, the second link is an pull request event on master.
The first is successful but the second is failed, the error is:
mkdir: cannot create directory ‘cov-analysis’: File exists

**Comment by vapier** [comment]
fairly certain it's failing because the action doesn't have access to secrets

you should update to the latest version and see if you get a better error message

**Comment by vapier** [comment]
feel free to re-open if you can provide more details
